Aklat/Controllers/CategoryController.cs
using Aklat.Models;
using Aklat.Reposatories.OrderRepo;
using Microsoft.AspNetCore.Mvc;
using System.ComponentModel.DataAnnotations.Schema;

namespace Aklat.Controllers
{ 
    public class CategoryController : Controller
    {
        private readonly ICategoryReposatory CategoryRepo;

        public CategoryController(ICategoryReposatory _category)
        {
            this.CategoryRepo = _category;
        }
        //

        public IActionResult Index()
        {
            return View(CategoryRepo.GetAll());
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Category category)
        {

            if (ModelState.IsValid)
            {
                CategoryRepo.Create(category);
                return RedirectToAction("");//may be index page
            }
            
            else 

            { 
                return View("category"); //may be create page
            }
            
        }


    }
}

Aklat/Controllers/OrderController.cs
using Akalat.ViewModel;
using Aklat.Models;
using Aklat.Reposatories.OrderProductRepo;
using Aklat.Reposatories.OrderRepo;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace Aklat.Controllers
{
    [Authorize]
    public class OrderController : Controller
    {
        private readonly IOrderReposatory orderReposatory;
        private readonly IOrderProductcs orderProductcsReposatory;

        public OrderController(IOrderReposatory orderReposatory, IOrderProductcs orderProductcsReposatory)
        {
            this.orderReposatory = orderReposatory;
            this.orderProductcsReposatory = orderProductcsReposatory;
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult GetPRO([FromBody] orderdatafromview orderdatafromview )
        {
            // Handle the received data, e.g., save it to a database
            var orderData = orderdatafromview.DataArray;
            var note = orderdatafromview.Note;
            var count = 0;
            Order order = new Order();

            foreach (var item in orderData)
            {

                count += item.ProductQuantity;
                order.TotalPrice += item.TotalPrice;


            }
            order.Count = count;
            order.OrderNote = note; 
            order.Date = DateTime.Now;

            order.UserID = User.Claims.FirstOrDefault(i=>i.Type==ClaimTypes.NameIdentifier).Value;

            orderReposatory.Create(order);

            orderReposatory.Save();

            foreach (var item in orderData)
            {
                order.OrderProducts?.Add(new OrderProduct()
                {
                    OrderID = order.ID,

                    ProductId = item.ProductID,

                    ProductQuantity = item.ProductQuantity,
                    ProductNote = item.ProductNote,

                });
            }

            orderReposatory.Save();

            //// Return a response if needed
            //return Ok("Data received and processed successfully.");
            return Redirect("/product/index");
        }

        [HttpPost]
        //public IActionResult Create([FromBody] test viewModel)
        //{

        //    //for (int i = 0; i < 1; i++)
        //    //{
        //    //    orderViewModelPost.orderProductHomes.Add(new OrderProductHome
        //    //    {
        //    //        ProductID = 1,
        //    //        ProductQuantity = 2,
        //    //    });
        //    //}
        //    //if(ModelState.IsValid)
        //    //{
        //    //Order order = new Order()
        //    //{
        //    //    OrderNote = orderViewModelPost.OrderNote,
        //    //    TotalPrice = 5455,
        //    //    Date = DateTime.Now,
        //    //    UserID = "56259fa0-7cd9-4470-a5be-9ecf8af913dd",
        //    //};
        //    //foreach (var item in orderViewModelPost.orderProductHomes)
        //    //{
        //    //    order.Count += item.ProductQuantity;
        //    //}

        //    //foreach (var item in orderViewModelPost.orderProductHomes)
        //    //{
        //    //    order.OrderProducts.Add(new OrderProduct()
        //    //    {
        //    //        OrderID = order.ID,
        //    //        ProductId = item.ProductID,
        //    //        ProductQuantity = item.ProductQuantity,
        //    //    });
        //    //}
        //    //orderReposatory.Create(order);
        //    //orderReposatory.Save();
        //    //return RedirectToAction("Index");
        //    List<OrderProductHome> receivedObjects = viewModel.MyObjects;
        //    return View("test", receivedObjects);

        //    //}
        //    //else { return View(); }

        //}
        public IActionResult Edit(int ID)
        {
            return View(orderReposatory.GetById(ID));
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Order order)
        {
            if (ModelState.IsValid)
            {
                orderReposatory.Update(order);
                return RedirectToAction("Index");
            }
            else { return View(order); }
        }


    }
}

Aklat/Controllers/ProductController.cs
using Akalat.ViewModel;
using Aklat.Models;
using Aklat.Reposatories.OrderRepo;
using Aklat.Reposatories.ProductRepo;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration.UserSecrets;

namespace Aklat.Controllers
{
    public class ProductController : Controller
    {
        private readonly IProductReposatory productRepoo;

        public ICategoryReposatory CategoryReposatory;

        public ProductController(IProductReposatory productRepoo , ICategoryReposatory categoryReposatory)
        {
            this.productRepoo = productRepoo;
            this.CategoryReposatory = categoryReposatory;
        }
        /// <summary>
        /// add new test  
        /// </summary>
        /// <returns></returns>
        public IActionResult Index()
        {
            return View(productRepoo.GetAll());

        }
        public IActionResult GetByID(int id)
        {
            var product = productRepoo.GetById(id);
              var OrderProductHome = new OrderProductHome()
              {
                  ProductID=product.Id,
                  ProductName=product.Name,
                  
                  Price=product.Price,

                  //orderProductHomes =new OrderProductHome
                  //{
                  //    ProductID=product.Id,
                  //    ProductName=product.Name,
                  //}
              };
           
            return PartialView("_Orderproduct", OrderProductHome);  
        }
        [HttpGet]
        public IActionResult Create()
        {
            ViewData["cat"] = CategoryReposatory.GetAll();

            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Product product)
        {
            ViewData["cat"] = CategoryReposatory.GetAll();

            if (ModelState.IsValid)
            {
                productRepoo.Create(product);
                productRepoo.Save();
                return RedirectToAction("Index");
            }
            else
            { 
                return View(product); 
            }

        }
        [HttpGet]
        public IActionResult Edit(int id)
        {
            ViewData["cat"] = CategoryReposatory.GetAll();
            
            
            return View(productRepoo.GetById(id));
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit( int id ,Product product)
        {
            ViewData["cat"] = CategoryReposatory.GetAll();

            if (ModelState.IsValid)
            {
                productRepoo.Update( id ,product);
                productRepoo.Save();
                return RedirectToAction("Index");
            }
            else
            {
                return View(product);
            }

        }
        public ActionResult Delete(int id)
        {
            productRepoo.Delete(id);
            productRepoo.Save();
           return RedirectToAction("Index");

        }

        
    }


}

Aklat/Views/Shared/_HomeLayout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <title>Talabat</title>
    <meta content="" name="description">
    <meta content="" name="keywords">

    <!-- Favicons -->
    <link href="~/assets/img/favicon.png" rel="icon">
    <link href="~/assets/img/apple-touch-icon.png" rel="apple-touch-icon">

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Roboto:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

    <!-- Vendor CSS Files -->
    <link href="~/assets/vendor/aos/aos.css" rel="stylesheet">
    <link href="~/assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/assets/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
    <link href="~/assets/vendor/boxicons/css/boxicons.min.css" rel="stylesheet">
    <link href="~/assets/vendor/glightbox/css/glightbox.min.css" rel="stylesheet">
    <link href="~/assets/vendor/swiper/swiper-bundle.min.css" rel="stylesheet">
    <link href="~/assets/css/homeStyle.css" rel="stylesheet">

    <!-- Template Main CSS File -->
    <link href="~/assets/css/style.css" rel="stylesheet">

    <!-- =======================================================
    * Template Name: BizLand
    * Updated: May 30 2023 with Bootstrap v5.3.0
    * Template URL: https://bootstrapmade.com/bizland-bootstrap-business-template/
    * Author: BootstrapMade.com
    * License: https://bootstrapmade.com/license/
    ======================================================== -->
</head>

<body>

    
    @RenderBody()

    <!-- Vendor JS Files -->
    <script src="~/assets/vendor/purecounter/purecounter_vanilla.js"></script>
    <script src="~/assets/vendor/aos/aos.js"></script>
    <script src="~/assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="~/assets/vendor/glightbox/js/glightbox.min.js"></script>
    <script src="~/assets/vendor/isotope-layout/isotope.pkgd.min.js"></script>
    <script src="~/assets/vendor/swiper/swiper-bundle.min.js"></script>
    <script src="~/assets/vendor/waypoints/noframework.waypoints.js"></script>
    <script src="~/assets/vendor/php-email-form/validate.js"></script>

    <!-- Template Main JS File -->
    <script src="~/assets/js/main.js"></script>
    @await RenderSectionAsync("Scripts", required: false)

</body>

</html>

Aklat/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <title>Talabat</title>
    <meta content="" name="description">
    <meta content="" name="keywords">

    <!-- Favicons -->
    <link href="~/assets/img/favicon.png" rel="icon">
    <link href="~/assets/img/apple-touch-icon.png" rel="apple-touch-icon">

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Roboto:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

    <!-- Vendor CSS Files -->
    <link href="~/assets/vendor/aos/aos.css" rel="stylesheet">
    <link href="~/assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/assets/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
    <link href="~/assets/vendor/boxicons/css/boxicons.min.css" rel="stylesheet">
    <link href="~/assets/vendor/glightbox/css/glightbox.min.css" rel="stylesheet">
    <link href="~/assets/vendor/swiper/swiper-bundle.min.css" rel="stylesheet">

    <!-- Template Main CSS File -->
    <link href="~/assets/css/style.css" rel="stylesheet">

    <!-- =======================================================
    * Template Name: BizLand
    * Updated: May 30 2023 with Bootstrap v5.3.0
    * Template URL: https://bootstrapmade.com/bizland-bootstrap-business-template/
    * Author: BootstrapMade.com
    * License: https://bootstrapmade.com/license/
    ======================================================== -->
</head>

<body>




    <!-- ======= Header ======= -->
    <header id="header" class="d-flex align-items-center">
        <div class="container d-flex align-items-center justify-content-between">

            <h1 class="logo"><a asp-controller="Home" asp-action="Index"><img src="~/images/white-logo.png" /></a></h1>
            <!-- Uncomment below if you prefer to use an image logo -->
            <!-- <a href="index.html" class="logo"><img src="~/assets/img/logo.png" alt=""></a>-->

            <nav id="navbar" class="navbar">
                <ul>
                    <li><a class="nav-link scrollto active" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a class="nav-link scrollto" asp-controller="Product" asp-action="Index">Product</a></li>
                    <li><a class="nav-link scrollto" asp-area="Admin" asp-controller="Order" asp-action="Index">Order</a></li>
                    <li><a class="nav-link scrollto" asp-controller="Category" asp-action="Index">Category</a></li>
                    <li><a class="nav-link scrollto " asp-controller="Account" asp-action="Login">Login</a></li>
                    <li><a class="nav-link scrollto" asp-controller="Account" asp-action="Register">Register</a></li>
                    <li><a style=" color:red" class="nav-link scrollto" asp-area="Admin" asp-controller="Home" asp-action="">Dashboard</a></li>

                    <li><a class="nav-link scrollto" href="#contact">Contact</a></li>
                </ul>
                <i class="bi bi-list mobile-nav-toggle"></i>
            </nav><!-- .navbar -->

        </div>
    </header><!-- End Header -->
    <div style="margin-bottom:20px;"></div>
    <!-- ======= Hero Section ======= -->
    <section id="hero" class="d-flex align-items-center">
        <div class="container" data-aos="zoom-out" data-aos-delay="100">
            <h1>Welcome  <span></span></h1>
            <h2>We are team of talented designers making websites with Bootstrap</h2>
            <div class="d-flex">
                <a href="#about" class="btn-get-started scrollto">Get Started</a>
                <a href="https://www.youtube.com/watch?v=jDDaplaOz7Q" class="glightbox btn-watch-video"><i class="bi bi-play-circle"></i><span>Watch Video</span></a>
            </div>
        </div>
    </section><!-- End Hero -->

    @RenderBody()



    <footer id="footer">

        <div class="footer-newsletter">
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-lg-6">
                        <h4>Join Our Newsletter</h4>
                        <p>Tamen quem nulla quae legam multos aute sint culpa legam noster magna</p>
                        <form action="" method="post">
                            <input type="email" name="email"><input type="submit" value="Subscribe">
                        </form>
                    </div>
                </div>
            </div>
        </div>

        <div class="footer-top">
            <div class="container">
                <div class="row">

                    <div class="col-lg-3 col-md-6 footer-contact">
                        <h3>BizLand<span>.</span></h3>
                        <p>
                            A108 Adam Street <br>
                            New York, NY 535022<br>
                            United States <br><br>
                            <strong>Phone:</strong> +1 5589 55488 55<br>
                            <strong>Email:</strong> info@example.com<br>
                        </p>
                    </div>

                    <div class="col-lg-3 col-md-6 footer-links">
                        <h4>Useful Links</h4>
                        <ul>
                            <li><i class="bx bx-chevron-right"></i> <a href="#">Home</a></li>
                            <li><i class="bx bx-chevron-right"></i> <a href="#">About us</a></li>
                            <li><i class="bx bx-chevron-right"></i> <a href="#">Services</a></li>
                            <li><i class="bx bx-chevron-right"></i> <a href="#">Terms of service</a></li>
                            <li><i class="bx bx-chevron-right"></i> <a href="#">Privacy policy</a></li>
                        </ul>
                    </div>

                    <div class="col-lg-3 col-md-6 footer-links">
                        <h4>Our Services</h4>
                        <ul>
                            <li><i class="bx bx-chevron-right"></i> <a href="#">Web Design</a></li>
                            <li><i class="bx bx-chevron-right"></i> <a href="#">Web Development</a></li>
                            <li><i class="bx bx-chevron-right"></i> <a href="#">Product Management</a></li>
                            <li><i class="bx bx-chevron-right"></i> <a href="#">Marketing</a></li>
                            <li><i class="bx bx-chevron-right"></i> <a href="#">Graphic Design</a></li>
                        </ul>
                    </div>

                    <div class="col-lg-3 col-md-6 footer-links">
                        <h4>Our Social Networks</h4>
                        <p>Cras fermentum odio eu feugiat lide par naso tierra videa magna derita valies</p>
                        <div class="social-links mt-3">
                            <a href="#" class="twitter"><i class="bx bxl-twitter"></i></a>
                            <a href="#" class="facebook"><i class="bx bxl-facebook"></i></a>
                            <a href="#" class="instagram"><i class="bx bxl-instagram"></i></a>
                            <a href="#" class="google-plus"><i class="bx bxl-skype"></i></a>
                            <a href="#" class="linkedin"><i class="bx bxl-linkedin"></i></a>
                        </div>
                    </div>

                </div>
            </div>
        </div>

        <div class="container py-4">
            <div class="copyright">
                &copy; Copyright <strong><span>BizLand</span></strong>. All Rights Reserved
            </div>
            <div class="credits">
                <!-- All the links in the footer should remain intact. -->
                <!-- You can delete the links only if you purchased the pro version. -->
                <!-- Licensing information: https://bootstrapmade.com/license/ -->
                <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/bizland-bootstrap-business-template/ -->
                Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a>
            </div>
        </div>
    </footer><!-- End Footer -->

    <div id="preloader"></div>
    <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

    <!-- Vendor JS Files -->
    <script src="~/assets/vendor/purecounter/purecounter_vanilla.js"></script>
    <script src="~/assets/vendor/aos/aos.js"></script>
    <script src="~/assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="~/assets/vendor/glightbox/js/glightbox.min.js"></script>
    <script src="~/assets/vendor/isotope-layout/isotope.pkgd.min.js"></script>
    <script src="~/assets/vendor/swiper/swiper-bundle.min.js"></script>
    <script src="~/assets/vendor/waypoints/noframework.waypoints.js"></script>
    <script src="~/assets/vendor/php-email-form/validate.js"></script>

    <!-- Template Main JS File -->
    <script src="~/assets/js/main.js"></script>
    @await RenderSectionAsync("Scripts", required: false)

</body>

</html>